[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python -m wb_bot.app.main"
restartPolicyType = "always"

[env]
ENVIRONMENT = "production"
DEBUG = "false"
PYTHONPATH = "/app"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"
