"""increase_encrypted_key_length

Revision ID: 8e976e36628a
Revises: postgresql_enums
Create Date: 2025-09-07 20:42:44.737761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e976e36628a'
down_revision: Union[str, None] = 'postgresql_enums'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api ключи')
    op.alter_column('api_keys', 'encrypted_key',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.drop_index(op.f('idx_apikey_user_valid'), table_name='api_keys')
    op.drop_index(op.f('idx_booking_task_status'), table_name='booking_results')
    op.create_index(op.f('ix_booking_results_wb_booking_id'), 'booking_results', ['wb_booking_id'], unique=False)
    op.drop_index(op.f('idx_user_active_monitoring'), table_name='monitoring_tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_user_active_monitoring'), 'monitoring_tasks', ['user_id', 'is_active', 'next_check'], unique=False)
    op.drop_index(op.f('ix_booking_results_wb_booking_id'), table_name='booking_results')
    op.create_index(op.f('idx_booking_task_status'), 'booking_results', ['task_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('idx_apikey_user_valid'), 'api_keys', ['user_id', 'is_valid', 'is_active'], unique=False)
    op.alter_column('api_keys', 'encrypted_key',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.create_table('api ключи',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('api ключи_pkey'))
    )
    # ### end Alembic commands ###
