"""add_browser_sessions_table

Revision ID: 6e180f1a2e24
Revises: 8e976e36628a
Create Date: 2025-09-08 01:02:28.098877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e180f1a2e24'
down_revision: Union[str, None] = '8e976e36628a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('browser_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('session_valid', sa.Boolean(), nullable=False),
    sa.Column('last_login_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_data_dir', sa.String(length=500), nullable=True),
    sa.Column('cookies_file', sa.String(length=500), nullable=True),
    sa.Column('wb_login_success', sa.Boolean(), nullable=True),
    sa.Column('last_successful_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_attempts', sa.Integer(), nullable=True),
    sa.Column('browser_fingerprint', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browser_sessions_id'), 'browser_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_browser_sessions_user_id'), 'browser_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_browser_sessions_user_id'), table_name='browser_sessions')
    op.drop_index(op.f('ix_browser_sessions_id'), table_name='browser_sessions')
    op.drop_table('browser_sessions')
    # ### end Alembic commands ###
